modLoader="javafml"
loaderVersion="[4,)"
license="PolyForm Shield License 1.0.0"

[[mods]]
modId="cavesdelight"
version="1.3.0"
displayName=" Cave's Delight"
displayURL="https://www.curseforge.com/minecraft/mc-mods/caves-delights"
logoFile="logo.png"
credits="Special thanks to my friends helping me out with gathering content ideas!!!"
authors="lennyvy"
description="FarmersDelight Addon for Cave Focused Content"

# Start of user code block mod configuration
# End of user code block mod configuration


# Start of user code block custom mixins
[[mixins]]
config = "mixins.cavesdelight.json"
# End of user code block custom mixins

[[dependencies.cavesdelight]]
modId="neoforge"
type="required"
versionRange="[21.1.190,)"
ordering="AFTER"
side="BOTH"

[[dependencies.cavesdelight]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="AFTER"
side="BOTH"


[[dependencies.cavesdelight]]
modId="jei"
type="optional"
versionRange="[0,)"
ordering="NONE"
side="BOTH"


# Start of user code block dependencies configuration
# End of user code block dependencies configuration
